# src/__init__.py
# This empty file marks the 'src' folder as a Python package.
# This allows us to import modules from src/ using:
#   from src.config import ...
#   from src.utils import ...
#   from src.fetch_mandi_prices import ...
